---
title: "Landing page"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

This landing page is created for p8105_hw4 by jc5457.

## Problem 1

Create a personal website at chengjialu.github.io, include:

1. A brief introductory landing page (this page)

2. A page giving my academic and professional experience:

    [About Me](about-me.html) includes 
    * the brief overview about me
    * my embeded resume
    * my contact


3. Links in the site navigation for my GitHub account, my email, and other professional networks.
    
    * Github and email icon can be found on the top right corner of the website.
    * Other contact information: See "contact" tab in  [About Me](about-me.html)


## Problem 2

Create a [flexdashboard](flexdashboard.html) using `plotly` for that includes at least three distinct plot types (e.g. scatterplots, line plots, bar plots, box plots, etc.). 

Here I use the `Instacart` dataset, and load it from the p8105.datasets package. The `instacart` dataset is large, thus here I only used the `product_name == "Spring Water"` and `add_to_cart_order >= 15` data (127 obs) to ensure a reasonable product. Using the filtered `Instacart` dataset, we can check the big customers' (purchase >= 15 in an order) behavior in purchasing Spring Water. 3 plots provided.

Format references from: https://pkgs.rstudio.com/flexdashboard/

